_wandb:
    value:
        cli_version: 0.18.2
        m: []
        python_version: 3.8.19
        t:
            "1":
                - 1
                - 41
                - 55
                - 105
            "2":
                - 1
                - 41
                - 55
                - 105
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.8.19
            "5": 0.18.2
            "8":
                - 1
                - 5
            "12": 0.18.2
            "13": linux-x86_64
epochs:
    value: 5
learning_rate:
    value: 0.001
